### ISSUE TITLE
Concessions Component

### ISSUE THREAD

**Issue by michellewehr** [michellewehr/MovieFoodie#9]
# User Story
* As a user, when I click the concessions tab in the navbar I will be brought to the section of the page featuring snacks. I will also be able to search more snacks by typing in an ingredient.

# Acceptance
* When I view the concessions section on the page, I will see a featured snack. 
* When I click on this snack I will be brought to the snack's recipe, displaying ingredients and recipe directions.
* When I enter an ingredient in the recipe search component, I will be shown images of snacks containing that ingredient.
* When I click on the image of the snack I will be brought to the recipe where I can view the recipe and ingredients.

**Comment by aileenbastos** [comment]
Concession page is MVP
